branches:
  except:
    - /travis-.*/

image: Visual Studio 2017

build_script:
  - nuget restore src\NUnitEngine\mock-assembly\mock-assembly.csproj
  - ps: .\build.ps1 -Target "Appveyor" -Configuration "Release"

# disable built-in tests.
test: off

artifacts:
- path: package\*.nupkg
- path: package\*.msi
- path: package\*.zip

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/testcentric/api/v2
    api_key:
      secure: wtAvJDVl2tfwiVcyLExFHLvZVfUWiQRHsfdHBFCNEATeCHo1Nd8JP642PfY8xhji
    skip_symbols: true
    on:
      branch: master
